name: build docker image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  DOCKER_REPO: jonoh/openvpn-client

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Prepare Dockerfile
        run: cat openvpn-client/Dockerfile >>Dockerfile

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: openvpn-client
          file: ./Dockerfile
          push: false
          load: true
          tags: intermediate

      - name: Get version
        id: get_version
        run: |
          VERSION=$(docker run --rm --entrypoint openvpn intermediate --version | head -n1 | grep -oP '(?<=OpenVPN )\d+\.\d+\.\d+(?= .*)')
          echo "::set-output name=DOCKER_TAG::$VERSION"

      - name: Build and push
        id: docker_build_push
        uses: docker/build-push-action@v5
        with:
          context: openvpn-client
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: "${{ env.DOCKER_REPO }}:${{ steps.get_version.outputs.DOCKER_TAG }}"

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          readme-filepath: ./readme.md
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.DOCKER_REPO }}
